# Generated by Django 5.0.2 on 2024-04-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_duomatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiotAccount",
            fields=[
                (
                    "puuid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("game_name", models.CharField(max_length=100)),
                ("tag_line", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiotSoloRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.CharField(max_length=255)),
                ("queue_type", models.CharField(max_length=255)),
                ("tier", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
                ("league_points", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("veteran", models.BooleanField()),
                ("inactive", models.BooleanField()),
                ("fresh_blood", models.BooleanField()),
                ("hot_streak", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="RiotToken",
            fields=[
                (
                    "id_token",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("access_token", models.CharField(max_length=1024)),
                ("token_type", models.CharField(max_length=255)),
                ("expires_in", models.IntegerField()),
                ("refresh_token", models.CharField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiotSummoner",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("puuid", models.CharField(max_length=100)),
                ("account_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("profile_icon_id", models.IntegerField()),
                ("revision_date", models.BigIntegerField()),
                ("summoner_level", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "riot_solo_rank",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.riotsolorank",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="riotsolorank",
            name="riot_summoner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.riotsummoner"
            ),
        ),
    ]
