# Generated by Django 5.0.2 on 2024-04-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_riotaccount_riotsolorank_riottoken_riotsummoner_and_more"),
        ("users", "0003_remove_appuser_summoner_info_appuser_summoner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="riot_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.riotaccount",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="riot_summoner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.riotsummoner",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="riot_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.riottoken",
            ),
        ),
    ]
